name: kidsacademybangla
description: "Play, Learn, and Grow in Bangla"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  audioplayers: ^6.5.1
  google_fonts: ^6.3.3
  flutter_staggered_grid_view: ^0.7.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/animals/
    - assets/images/fruits/
    #
    - assets/sounds/
    - assets/sounds/animals/
    - assets/sounds/fruits/
    - assets/sounds/colors/
    - assets/sounds/bangla_vowels/
    - assets/sounds/bangla_consonants/
    - assets/sounds/bangla_numbers/
    - assets/sounds/english_alphabets/
    - assets/sounds/english_numbers/
    - assets/sounds/arabic_alphabets/
    - assets/sounds/arabic_numbers/
    - assets/sounds/english_rhymes/
    - assets/sounds/bangla_rhymes/
 
 
 
 

 
 

 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
